name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
     CODE_COVERAGE_THRESHOLD: 20
     LOCAL_CODE_COVERAGE_OPTIN_FLAG: ${{ vars.CODE_COVERAGE_OPTIN_FLAG }}


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v1
      
    - name: Use variable
      run:  echo "LOCAL_CODE_COVERAGE_OPTIN_FLAG:$LOCAL_CODE_COVERAGE_OPTIN_FLAG"
      
    - name: Use Node.js 18.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0

    - name: Install Angular CLI and dependencies
      run: |
        npm install -g @angular/cli --force
        npm install --save-dev @angular-devkit/build-angular --force

    - name: Install dependencies
      run: npm ci

    - name: Set up Xvfb
      run: |
        export DISPLAY=:99
        sudo apt-get install -y xvfb
        Xvfb -screen 0 1024x768x24 :99 &

    - name: Run tests
      run: |
        npm run build --prod
        xvfb-run -a ng test --configuration=development --browsers=ChromeHeadless --code-coverage --watch=false --progress=true
    
        - name: Docker Build and Push
          uses: docker/build-push-action@v2
            with:
            context: .
            push: true
            tags: v1.0, latest
