name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 18.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0

    - name: Install Angular CLI and dependencies
      run: |
        npm install -g @angular/cli --force
        npm install --save-dev @angular-devkit/build-angular --force

    - name: Install dependencies
      run: npm ci

    - name: Set up Xvfb
      run: |
        export DISPLAY=:99
        sudo apt-get install -y xvfb
        Xvfb -screen 0 1024x768x24 :99 &

    - name: Run tests
      run: |
        npm run build --prod
        # xvfb-run -a ng test --configuration=development
        xvfb-run -a ng test --configuration=development --browsers=ChromeHeadless --code-coverage --watch=false --progress=true
        # timeout-minutes: 4
        
    - name: Check code coverage
      run: |
        COVERAGE_THRESHOLD=20
        coverage=$(sed -n 's/.*Statements \([0-9.]*\)%.*/\1/p' ./coverage/$(Build.SourcesDirectory)/index.html)
        echo "Actual coverage is: $coverage%"
        
        coverage1=$(sed -nE 's/.*([0-9]+[.][0-9]+)% Statements.*/\1/p' ./coverage/$(Build.SourcesDirectory)/index.html)
        echo "Actual coverage1 is: $coverage1%"
        
