name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 18.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0

    - name: Install Angular CLI and dependencies
      run: |
        npm install -g @angular/cli --force
        npm install --save-dev @angular-devkit/build-angular --force

    - name: Install dependencies
      run: npm ci

    - name: Set up Xvfb
      run: |
        export DISPLAY=:99
        sudo apt-get install -y xvfb
        Xvfb -screen 0 1024x768x24 :99 &

    - name: Run tests
      run: |
        npm run build --prod
        # xvfb-run -a ng test --configuration=development
        xvfb-run -a ng test --configuration=development --browsers=ChromeHeadless --code-coverage --watch=false --progress=true
        # timeout-minutes: 4
        
    - name: Check code coverage
      run: |
        COVERAGE_THRESHOLD=20
        # coverage=$(grep -oP "(?<=statements.\s)(\d+.\d+)" ./coverage/angular-inmemory-api/index.html)
        coverage=$(grep -oP "(?<=Statements.\s)(\d+.\d+)" ./coverage/angular-inmemory-api/index.html)
         echo "Actual coverage is : $coverage%"
        if (( $(echo "$coverage < $COVERAGE_THRESHOLD" | bc -l) )); then
          echo "Code coverage is less than $COVERAGE_THRESHOLD%. Sending message..."
          # Add your custom logic here to send a message or take any other action
          # For example, you can use a messaging service or create a GitHub issue
          # You can also use the GitHub API to add a comment or set the workflow status
          exit 1  # This will mark the workflow as failed
        else
          echo "Code coverage is acceptable: $coverage%"
        fi
