name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 18.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: npm ci

    - name: Set up Xvfb
      run: |
        export DISPLAY=:99
        sudo apt-get install -y xvfb
        Xvfb -screen 0 1024x768x24 :99 &

    - name: Run tests
      run: |
        npm run build --prod
        xvfb-run -a ng test --configuration=ci
